### ISSUE TITLE
Compilation fails for c++23 due to missing header.

### ISSUE THREAD

**Issue by bruno-j-nicoletti** [jbaldwin/libcoro#247]
Building with clang 17.0.6 on macos, for c++23, compilation fails for `sync_wait.hpp` with the following warning...

```
libcoro/include/coro/sync_wait.hpp:44:10: error: no type named 'exception_ptr' in namespace 'std'; did you mean 'exception'?
```

I can fix in locally with a  `#include <exception>` in `sync_wait.hpp`

**Comment by jbaldwin** [comment]
It looks like #246 probably adds the header you need, so I think maybe just CI for macos would be an awesome addition.

I've recently been thinking also about swapping the linux kernel epoll functions with something like libuv, I believe it should be reasonable similar in performance but it would support a lot more functionality cross platform. This is probably worth an investigation at least to see how hard it would be to change `coro::io_scheduler` to use that internally instead of linux epoll.

**Comment by bruno-j-nicoletti** [comment]
They beat me to it by a day! I can have a go at getting a macos CI PR out. Those always make me cry though.

**Comment by jbaldwin** [comment]
I'd really appreciate. And yeah CI isn't always the most fun but looks like its being used so it would be awesome to add it on the list of supported OSs!

**Comment by bruno-j-nicoletti** [comment]
I have to install clang-17 on the build machine, as the default clang-15 on macos is so far behind. Also, -DLIBCORO_FEATURE_NETWORKING=ON won't work as `<sys/epoll.h>` is missing on macos

**Comment by jbaldwin** [comment]
Makes sense, I've also added #248 to start looking at better cross platform support for all features.

**Comment by bruno-j-nicoletti** [comment]
PR is out. I had to tweak CMakelists.txt to make clang-17 link properly on macos.
