### ISSUE TITLE
Do not let exceptions propagate and silently exit(0)

### ISSUE THREAD

**Issue by niansa** [jbaldwin/libcoro#93]
... because it makes it all pretty hard to debug.

**Comment by jbaldwin** [comment]
Are you referring to `coro::thread_pool` and or `coro::io_scheduler`?  Most of the coro library functions should be correctly annotated with `@throws` but its possible I missed a few, feel free to point any out if you find them!

In regards to your question though how would you suggest reporting to the user of the library that something was thrown?  It could be possible to force something like `coro::result<T, Exception>` on the thread pool return for the user to decompose it into either the T or Exception (this would be extremely similar to how Rust handles things in general).  However, I'm not sure this works so well on the `coro::io_schedueler` since everything is generally async and most likely won't have a user land thread to return to if an exception is thrown.  They could just be caught and discarded?  Not sure I like this solution either since it will hide problems in user code -- ideally the user probably needs a root try/catch in their `io_scheduler` tasks.

**Comment by niansa** [comment]
I'd just write the exception details to std::cerr and abort(). libasync does that and it helped me debugging really well.

**Comment by jbaldwin** [comment]
I don't like the design idea of unconditionally writing directly to std::cerr automatically, but maybe a debug mode on those classes could be enabled to do so.

**Comment by niansa** [comment]
Well, I think it's possible to just terminate() instead.

**Comment by niansa** [comment]
Just came to my mind, you could also let the main loop rethrow that exception so it can then be handled from synchronous code.

**Comment by jbaldwin** [comment]
I've been pretty busy on other things in life lately so this project hasn't seen much change in a while. But I wonder if a throw/nothrow argument to io_scheduler constructor would be useful? then it could be turned on in a debug environment.  I kind of like the idea if its enabled the main io_scheduler thread that is polling could re-throw the exception if this feature is enabled.  This might be basically what you are suggestion?

**Comment by jbaldwin** [comment]
Its been a year, but I think my plan is just to remove thrown exceptions due to the global lock around them.  Closing in favor of #87
