### ISSUE TITLE
Event but FIFO?

### ISSUE THREAD

**Issue by niansa** [jbaldwin/libcoro#95]
Hey, I need an event type that is FIFO instead of LIFO. This is because tasks HAVE TO be resumed in the same order as they were suspended in.

Is there anything like that in the current implementation?

**Comment by jbaldwin** [comment]
FIFO incurs a heavy cost on the `coro::event` structure, sometimes being unfair makes things faster overall.  I think it would require adding an std::mutex and another tail pointer to get it to work correctly but there are other structures like `coro::shared_mutex` which already do this so its probably not too difficult to do.  I'd probably want it to be a separate class though since it has some major tradeoffs in performance and structure size.

You might be able to use `coro::shared_mutex` right now with everything as an exclusive locker if you don't care about parallelizing the waiters?  It does a full std::mutex lock though so it'll be a lot slower than `coro::event` that just uses atomics.

**Comment by niansa** [comment]
Perfect, sounds good, thanks. I'll try that or just wait until it's improved ;-)
